rvm:
  - 2.2
  - 2.3.5
  - 2.4.3
  - 2.5.0  
  - ruby-head

cache:
  directories:
  - $HOME/gnatsd

before_install:
  - bash ./scripts/install_gnatsd.sh

before_script:
  - export PATH=$HOME/gnatsd:$PATH

sudo: required
dist: trusty

matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      jdk: openjdk7
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      jdk: openjdk8
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      jdk: openjdk7
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      jdk: openjdk8
    - rvm: jruby
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false' JAVA_OPTS='-Djava.security.egd=file:///dev/urandom'
      jdk: oraclejdk8
    - rvm: ruby-head

addons:
  hosts:
    - server-A.clients.nats-service.localhost
    - server-A.clients.fake-nats-service.localhost
    - server-A.routes.nats-service.localhost
    - server-A.routes.fake-nats-service.localhost
